import { GetAllWcOrderRequestData } from "@/woocommerce/orders/get-all";

export interface WcOrdersInterface {
    id: 58138,
    parent_id: 0,
    status: GetAllWcOrderRequestData["status"],
    currency: 'AED',
    version: string,
    prices_include_tax: false,
    date_created: string,
    date_modified: string,
    discount_total: string,
    discount_tax: string,
    shipping_total: string,
    shipping_tax: string,
    cart_tax: string,
    total: string,
    total_tax: string,
    customer_id: number,
    order_key: string,
    billing: {},
    shipping: {},
    payment_method: string,
    payment_method_title: string,
    transaction_id: string,
    customer_ip_address: string,
    customer_user_agent: string,
    created_via: string,
    customer_note: string,
    date_completed: string | null,
    date_paid: string | null,
    cart_hash: string,
    number: string,
    refunds: [],
    payment_url: string,
    is_editable: boolean,
    needs_payment: boolean,
    needs_processing: boolean,
    date_created_gmt: string,
    date_modified_gmt: string,
    date_completed_gmt: string | null,
    date_paid_gmt: string | null,
    currency_symbol: 'AED',
    _links: {}
}